#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2023 AirMettle, Inc.
#  All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../..)

TEST_FILE = nvme_kv_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk